# Generated by Django 4.0.2 on 2022-09-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('returns', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('equity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.equities')),
            ],
        ),
    ]
