# Generated by Django 4.0.2 on 2022-09-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('returns', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('equity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.equities')),
            ],
        ),
        migrations.DeleteModel(
            name='returns',
        ),
    ]
