# Generated by Django 4.0.2 on 2022-09-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_daily_returns_delete_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_returns',
            name='returns',
        ),
    ]
