# Generated by Django 4.0.2 on 2022-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_daily_returns_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_returns',
            name='equity_id',
            field=models.IntegerField(),
        ),
    ]
