# Generated by Django 4.0.2 on 2022-09-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_daily_returns_equity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_returns',
            name='returns',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='daily_returns',
            name='equity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.equities'),
        ),
    ]
